sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "assets/img"
    values:
      image: true

title: Blog
name: Welcome DangHao's blog!
description: Stay hungry，stay foolish! When I am young, what I have did?

#title: Minimalism
#name: minimalism
#description: Minimalism is a jekyll theme for minimalist

github: https://github.com/gejiangwendi/gejiangwendi.github.io
#rss: true

plugins:
  - rouge
  - kramdown
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

exclude:
  - script
  - docs
  - vendor
  - Gemfile
  - Gemfile.lock
